[theme]
base="light"
primaryColor="#FF0000"  # Red color for accents
backgroundColor="#FFFFFF"  # White background
secondaryBackgroundColor="#F0F0F0"  # Light grey for slight contrast
textColor="#333333"  # Dark text color
font="sans serif"